/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas.individu;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author faldi
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        basePanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        galleryButton = new javax.swing.JPanel();
        Member = new javax.swing.JLabel();
        kotakMember = new javax.swing.JPanel();
        homeButton = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        kotakHome = new javax.swing.JPanel();
        profileButton = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        kotakProfile = new javax.swing.JPanel();
        settingButton = new javax.swing.JPanel();
        Setting = new javax.swing.JLabel();
        kotakSetting = new javax.swing.JPanel();
        logoutButton = new javax.swing.JPanel();
        Logout = new javax.swing.JLabel();
        iconAbout1 = new javax.swing.JLabel();
        aboutButton = new javax.swing.JPanel();
        About = new javax.swing.JLabel();
        iconAbout = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        memberPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        profilePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        txtNama1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jcheckbox = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        txtNama2 = new javax.swing.JLabel();
        txtNama3 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        txtNama4 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        settingPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        sliderFont = new javax.swing.JSlider();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        spinnerFont = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        basePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(34, 67, 153));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        galleryButton.setBackground(new java.awt.Color(34, 67, 153));
        galleryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                galleryButtonMouseClicked(evt);
            }
        });
        galleryButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Member.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Member.setForeground(new java.awt.Color(255, 255, 255));
        Member.setText("Member");
        galleryButton.add(Member, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 4, -1, -1));

        kotakMember.setBackground(new java.awt.Color(34, 67, 153));

        javax.swing.GroupLayout kotakMemberLayout = new javax.swing.GroupLayout(kotakMember);
        kotakMember.setLayout(kotakMemberLayout);
        kotakMemberLayout.setHorizontalGroup(
            kotakMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        kotakMemberLayout.setVerticalGroup(
            kotakMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        galleryButton.add(kotakMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        menuPanel.add(galleryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, 30));

        homeButton.setBackground(new java.awt.Color(34, 67, 153));
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
        });
        homeButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Home");
        homeButton.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 10));

        kotakHome.setBackground(new java.awt.Color(34, 67, 153));

        javax.swing.GroupLayout kotakHomeLayout = new javax.swing.GroupLayout(kotakHome);
        kotakHome.setLayout(kotakHomeLayout);
        kotakHomeLayout.setHorizontalGroup(
            kotakHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        kotakHomeLayout.setVerticalGroup(
            kotakHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        homeButton.add(kotakHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        menuPanel.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 30));

        profileButton.setBackground(new java.awt.Color(34, 67, 153));
        profileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileButtonMouseClicked(evt);
            }
        });
        profileButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("Profile");
        profileButton.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 10));

        kotakProfile.setBackground(new java.awt.Color(34, 67, 153));

        javax.swing.GroupLayout kotakProfileLayout = new javax.swing.GroupLayout(kotakProfile);
        kotakProfile.setLayout(kotakProfileLayout);
        kotakProfileLayout.setHorizontalGroup(
            kotakProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        kotakProfileLayout.setVerticalGroup(
            kotakProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        profileButton.add(kotakProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        menuPanel.add(profileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 100, 30));

        settingButton.setBackground(new java.awt.Color(34, 67, 153));
        settingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingButtonMouseClicked(evt);
            }
        });
        settingButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Setting.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Setting.setForeground(new java.awt.Color(255, 255, 255));
        Setting.setText("Setting");
        settingButton.add(Setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 4, -1, -1));

        kotakSetting.setBackground(new java.awt.Color(34, 67, 153));

        javax.swing.GroupLayout kotakSettingLayout = new javax.swing.GroupLayout(kotakSetting);
        kotakSetting.setLayout(kotakSettingLayout);
        kotakSettingLayout.setHorizontalGroup(
            kotakSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        kotakSettingLayout.setVerticalGroup(
            kotakSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        settingButton.add(kotakSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        menuPanel.add(settingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 100, 30));

        logoutButton.setBackground(new java.awt.Color(34, 67, 153));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        logoutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logout.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Log out");
        logoutButton.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 4, -1, -1));

        iconAbout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon log out.png"))); // NOI18N
        logoutButton.add(iconAbout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        menuPanel.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 100, 30));

        aboutButton.setBackground(new java.awt.Color(34, 67, 153));
        aboutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutButtonMouseClicked(evt);
            }
        });
        aboutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        About.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        About.setForeground(new java.awt.Color(255, 255, 255));
        About.setText("About");
        aboutButton.add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 4, -1, -1));

        iconAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon about.png"))); // NOI18N
        aboutButton.add(iconAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        menuPanel.add(aboutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 100, 30));

        basePanel.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 530));

        mainPanel.setBackground(new java.awt.Color(34, 67, 153));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(34, 67, 153));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bebas Neue Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(244, 173, 71));
        jLabel2.setText("home");
        homePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mars.jpg"))); // NOI18N
        homePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(34, 67, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Mars adalah planet terdekat keempat dari Matahari. Namanya diambil dari dewa \nperang Romawi, Mars. Planet ini sering dijuluki sebagai \"planet merah\" karena \ntampak dari jauh berwarna kemerah-kemerahan. Ini disebabkan oleh \nkeberadaan besi(III) oksida di permukaan planet Mars. Mars adalah planet \nbebatuan dengan atmosfer yang tipis. Di permukaan Mars terdapat kawah, \ngunung berapi, lembah, gurun, dan tudung es. Periode rotasi dan siklus \nmusim Mars mirip dengan Bumi. Di Mars berdiri Olympus Mons, gunung \ntertinggi di Tata Surya, dan Valles Marineris, lembah terbesar di Tata Surya. \nSelain itu, di belahan utara terdapat cekungan Borealis yang meliputi 40% \npermukaan Mars.");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        homePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 450, 160));

        mainPanel.add(homePanel, "card2");

        memberPanel.setBackground(new java.awt.Color(34, 67, 153));
        memberPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Bebas Neue Bold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(244, 173, 71));
        jLabel7.setText("member");
        memberPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        memberPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 100));

        mainPanel.add(memberPanel, "card3");

        profilePanel.setBackground(new java.awt.Color(34, 67, 153));
        profilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(244, 173, 71));
        jLabel6.setText("Change password");
        profilePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setText("Nama");
        profilePanel.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 20));

        jTextField1.setBackground(new java.awt.Color(34, 67, 153));
        jTextField1.setForeground(new java.awt.Color(244, 173, 71));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        profilePanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 120, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jenis Kelamin");
        profilePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        maleRadio.setBackground(new java.awt.Color(34, 67, 153));
        buttonGroup1.add(maleRadio);
        maleRadio.setForeground(new java.awt.Color(244, 173, 71));
        maleRadio.setText("Laki-laki");
        profilePanel.add(maleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        femaleRadio.setBackground(new java.awt.Color(34, 67, 153));
        buttonGroup1.add(femaleRadio);
        femaleRadio.setForeground(new java.awt.Color(244, 173, 71));
        femaleRadio.setText("Perempuan");
        profilePanel.add(femaleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        txtNama1.setForeground(new java.awt.Color(255, 255, 255));
        txtNama1.setText("Password lama");
        profilePanel.add(txtNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 120, 20));

        jTextField2.setBackground(new java.awt.Color(34, 67, 153));
        jTextField2.setForeground(new java.awt.Color(244, 173, 71));
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        profilePanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 120, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("(DD/MM/YYYY)");
        profilePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, 20));

        jFormattedTextField1.setBackground(new java.awt.Color(34, 67, 153));
        jFormattedTextField1.setBorder(null);
        jFormattedTextField1.setForeground(new java.awt.Color(244, 173, 71));
        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        profilePanel.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 70, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cabang Member");
        profilePanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 110, 20));

        jSeparator2.setBackground(new java.awt.Color(240, 204, 153));
        profilePanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 70, 10));

        jSeparator3.setBackground(new java.awt.Color(240, 204, 153));
        profilePanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 120, 10));

        jSeparator4.setBackground(new java.awt.Color(240, 204, 153));
        profilePanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 120, 10));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tanggal Lahir");
        profilePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 80, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wiraswasta", "Guru", "Polisi", "Pelajar" }));
        profilePanel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 160, -1));

        jCheckBox1.setBackground(new java.awt.Color(34, 67, 153));
        jCheckBox1.setForeground(new java.awt.Color(244, 173, 71));
        jCheckBox1.setText("Membaca");
        profilePanel.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(34, 67, 153));
        jCheckBox2.setForeground(new java.awt.Color(244, 173, 71));
        jCheckBox2.setText("Menulis");
        profilePanel.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jcheckbox.setBackground(new java.awt.Color(34, 67, 153));
        jcheckbox.setForeground(new java.awt.Color(244, 173, 71));
        jcheckbox.setText("Menabung");
        profilePanel.add(jcheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pekerjaan");
        profilePanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 60, 20));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Bandung", "Jakarta", "Cilacap", "Sumedang" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        profilePanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 140, 60));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Hobi");
        profilePanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 30, 20));

        jButton1.setBackground(new java.awt.Color(244, 173, 71));
        jButton1.setForeground(new java.awt.Color(34, 67, 153));
        jButton1.setText("Simpan");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        profilePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 70, 40));
        profilePanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 460, -1));

        jLabel17.setFont(new java.awt.Font("Bebas Neue Bold", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(244, 173, 71));
        jLabel17.setText("profile");
        profilePanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPasswordField1.setText("jPashhy");
        profilePanel.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 70, -1));

        txtNama2.setForeground(new java.awt.Color(255, 255, 255));
        txtNama2.setText("Email");
        profilePanel.add(txtNama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 20));

        txtNama3.setForeground(new java.awt.Color(255, 255, 255));
        txtNama3.setText("Password baru");
        profilePanel.add(txtNama3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 120, 20));

        jPasswordField2.setText("jPashhy");
        profilePanel.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 70, -1));

        txtNama4.setForeground(new java.awt.Color(255, 255, 255));
        txtNama4.setText("Password baru lagi");
        profilePanel.add(txtNama4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 110, 20));

        jPasswordField3.setText("jPashhy");
        profilePanel.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 70, -1));

        jButton2.setBackground(new java.awt.Color(244, 173, 71));
        jButton2.setForeground(new java.awt.Color(34, 67, 153));
        jButton2.setText("Simpan");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        profilePanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 70, 40));
        profilePanel.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        mainPanel.add(profilePanel, "card3");

        settingPanel.setBackground(new java.awt.Color(34, 67, 153));
        settingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Bebas Neue Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(244, 173, 71));
        jLabel5.setText("Setting");
        settingPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indonesia", "English", "Jawa", "Sunda" }));
        settingPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bahasa         :");
        settingPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        sliderFont.setBackground(new java.awt.Color(34, 67, 153));
        sliderFont.setForeground(new java.awt.Color(244, 173, 71));
        sliderFont.setMajorTickSpacing(2);
        sliderFont.setMaximum(20);
        sliderFont.setPaintLabels(true);
        sliderFont.setPaintTicks(true);
        sliderFont.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderFontStateChanged(evt);
            }
        });
        settingPanel.add(sliderFont, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 320, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ukuran Font :");
        settingPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Test");
        settingPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jButton3.setBackground(new java.awt.Color(244, 173, 71));
        jButton3.setForeground(new java.awt.Color(34, 67, 153));
        jButton3.setText("Apply");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        settingPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 70, 40));

        spinnerFont.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        settingPanel.add(spinnerFont, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ukuran Font :");
        settingPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Test");
        settingPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jButton4.setBackground(new java.awt.Color(244, 173, 71));
        jButton4.setForeground(new java.awt.Color(34, 67, 153));
        jButton4.setText("Simpan");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        settingPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 70, 40));

        mainPanel.add(settingPanel, "card4");

        basePanel.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 480, 450));

        jSeparator1.setBackground(new java.awt.Color(240, 204, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        basePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 20, -1, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Background main menu.png"))); // NOI18N
        basePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseClicked
        // TODO add your handling code here
        
       //mengganti button yang di klik
       profile.setForeground(new Color(240, 204, 153));
       kotakProfile.setBackground(new Color(240, 204, 153));
       
       //mengganti button yang lain
       home.setForeground(new Color(240,240,240));
       kotakHome.setBackground(new Color(34,67,153));
       Setting.setForeground(new Color(240,240,240));
       kotakSetting.setBackground(new Color(34,67,153));
       Member.setForeground(new Color(240,240,240));
       kotakMember.setBackground(new Color(34,67,153));
       
       //menghapus panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //menambahkan panel
        mainPanel.add(profilePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
       
    }//GEN-LAST:event_profileButtonMouseClicked

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        // TODO add your handling code here:
        
        //mengganti button yang di klik
       home.setForeground(new Color(240, 204, 153));
       kotakHome.setBackground(new Color(240, 204, 153));
       
       //mengganti button yang lain
       profile.setForeground(new Color(240,240,240));
       kotakProfile.setBackground(new Color(34,67,153));
       Setting.setForeground(new Color(240,240,240));
       kotakSetting.setBackground(new Color(34,67,153));
       Member.setForeground(new Color(240,240,240));
       kotakMember.setBackground(new Color(34,67,153));
       
       //menghapus panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //menambahkan panel
        mainPanel.add(homePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
       
    }//GEN-LAST:event_homeButtonMouseClicked

    private void settingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingButtonMouseClicked
        // TODO add your handling code here:
      
       //mengganti button yang di klik 
       Setting.setForeground(new Color(240, 204, 153));
       kotakSetting.setBackground(new Color(240, 204, 153));
       
       //mengganti button yang lain
       home.setForeground(new Color(240,240,240));
       kotakHome.setBackground(new Color(34,67,153));
       profile.setForeground(new Color(240,240,240));
       kotakProfile.setBackground(new Color(34,67,153));
       Member.setForeground(new Color(240,240,240));
       kotakMember.setBackground(new Color(34,67,153));
       
       //menghapus panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //menambahkan panel
        mainPanel.add(settingPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_settingButtonMouseClicked

    private void aboutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseClicked
        // TODO add your handling code here:
        
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_aboutButtonMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        
        int dialogbtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Apakah anda yakin akan keluar?", "PERINGATAN", dialogbtn);

        if (dialogResult == 0) {
            Login login = new Login();
        login.setVisible(true);
        dispose();
        } else {

        }
        
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void galleryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_galleryButtonMouseClicked
        // TODO add your handling code here:
       
        //mengganti button yang di klik 
       Member.setForeground(new Color(240, 204, 153));
       kotakMember.setBackground(new Color(240, 204, 153));
       
       //mengganti button yang lain
       home.setForeground(new Color(240,240,240));
       kotakHome.setBackground(new Color(34,67,153));
       profile.setForeground(new Color(240,240,240));
       kotakProfile.setBackground(new Color(34,67,153));
       Setting.setForeground(new Color(240,240,240));
       kotakSetting.setBackground(new Color(34,67,153));
       
       //menghapus panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //menambahkan panel
        mainPanel.add(memberPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_galleryButtonMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void sliderFontStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderFontStateChanged
        // TODO add your handling code here:
        jLabel19.setFont(new Font(jLabel14.getFont().getName(), jLabel14.getFont().getStyle(), sliderFont.getValue()));
    }//GEN-LAST:event_sliderFontStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel14.setFont(new Font(jLabel14.getFont().getName(), jLabel14.getFont().getStyle(), (int) spinnerFont.getValue()));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Member;
    private javax.swing.JLabel Setting;
    private javax.swing.JPanel aboutButton;
    private javax.swing.JPanel basePanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JPanel galleryButton;
    private javax.swing.JLabel home;
    private javax.swing.JPanel homeButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel iconAbout;
    private javax.swing.JLabel iconAbout1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JCheckBox jcheckbox;
    private javax.swing.JPanel kotakHome;
    private javax.swing.JPanel kotakMember;
    private javax.swing.JPanel kotakProfile;
    private javax.swing.JPanel kotakSetting;
    private javax.swing.JPanel logoutButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JPanel memberPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel profile;
    private javax.swing.JPanel profileButton;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JPanel settingButton;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JSlider sliderFont;
    private javax.swing.JSpinner spinnerFont;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtNama1;
    private javax.swing.JLabel txtNama2;
    private javax.swing.JLabel txtNama3;
    private javax.swing.JLabel txtNama4;
    // End of variables declaration//GEN-END:variables
}
